⤵️ automation(synchronize) Applying changes from upstream repository.

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -1,5 +1,6 @@
 ---
 version: '3'
+
 includes:
   ansible: ./.config/taskfiles/ansible/Taskfile.yml
   ansible:ansibler: ./.config/taskfiles/ansible/Taskfile-ansibler.yml
@@ -26,6 +27,7 @@ includes:
   git: ./.config/taskfiles/git/Taskfile.yml
   git:github: ./.config/taskfiles/git/Taskfile-github.yml
   git:gitlab: ./.config/taskfiles/git/Taskfile-gitlab.yml
+  git:gitomatic: ./.config/taskfiles/git/Taskfile-gitomatic.yml
   git:hook: ./.config/taskfiles/git/Taskfile-hook.yml
   go: ./.config/taskfiles/go/Taskfile.yml
   go:goreleaser: ./.config/taskfiles/go/Taskfile-goreleaser.yml
@@ -34,6 +36,7 @@ includes:
   install: ./.config/taskfiles/install/Taskfile.yml
   install:ansible: ./.config/taskfiles/install/Taskfile-ansible.yml
   install:apt: ./.config/taskfiles/install/Taskfile-apt.yml
+  install:gh: ./.config/taskfiles/install/Taskfile-gh.yml
   install:github: ./.config/taskfiles/install/Taskfile-github.yml
   install:go: ./.config/taskfiles/install/Taskfile-go.yml
   install:npm: ./.config/taskfiles/install/Taskfile-npm.yml
@@ -83,7 +86,9 @@ includes:
   web:ionic: ./.config/taskfiles/web/Taskfile-ionic.yml
   web:nx: ./.config/taskfiles/web/Taskfile-nx.yml
   web:profile: ./.config/taskfiles/web/Taskfile-profile.yml
+
 output: interleaved
+
 vars:
   DOCKERHUB_PROFILE:
     sh: |
@@ -134,7 +139,11 @@ vars:
   GROUP_EXEC_ASYNC: 'false'
   # yamllint disable rule:line-length
   IGNORE_FOLDERS: >-
-    -path './.autodoc/*' -o -path './.cache/*' -o -path './.common*' -o -path './.config/*' -o -path './.git/*' -o -path './.github/*' -o -path './.gitlab/*' -o -path './.husky/*' -o -path './.modules/*' -o -path './.npm/*' -o -path './.pnpm-store/*' -o -path './.shared/*' -o -path './.task/*' -o -path './.venv/*' -o -path './.vscode/*' -o -path './build/*' -o -path './dist/*' -o -path './node_modules/*' -o -path './roles/*' -o -name pnpm-lock.yaml -o -name package-lock.json -o -name poetry.lock -o -name '.variables.json'
+    -path './.autodoc/*' -o -path './.cache/*' -o -path './.common*' -o -path './.config/*' -o -path './.git/*' -o
+    -path './.github/*' -o -path './.gitlab/*' -o -path './.husky/*' -o -path './.modules/*' -o -path './.npm/*' -o
+    -path './.pnpm-store/*' -o -path './.shared/*' -o -path './.task/*' -o -path './.venv/*' -o -path './.vscode/*' -o
+    -path './build/*' -o -path './dist/*' -o -path './node_modules/*' -o -path './roles/*' -o -name pnpm-lock.yaml -o
+    -name package-lock.json -o -name poetry.lock -o -name '.variables.json'
   INIT_SCRIPT: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/scripts/update-init.sh
   LOG_FIX:
     sh: chmod +x .config/log
@@ -155,13 +164,6 @@ vars:
       elif type pnpm &> /dev/null; then
         echo 'pnpm '
       fi
-  NPX_PACKAGE:
-    sh: |
-      if type pnpx &> /dev/null; then
-        echo 'pnpx'
-      elif type pnpm &> /dev/null; then
-        echo 'pnpm'
-      fi
   PROJECT_TYPE:
     sh: |
       if type jq &> /dev/null && [ -f package.json ]; then VER="$(jq -r '.blueprint.group' package.json)"; if [ "$VER" == 'null' ]; then echo TYPE="$GROUP_TYPE"; else TYPE="$VER"; fi; else TYPE="$GROUP_TYPE"; fi
@@ -180,20 +182,41 @@ vars:
   # yamllint enable rule:line-length
   PYTHON_HANDLE:
     sh: |
-      if [ -n "$NO_INSTALL_POETRY" ] || ! type poetry > /dev/null; then
-        echo ''
-      else
+      if type poetry > /dev/null; then
         echo 'poetry run '
+      else
+        echo ''
       fi
   PYTHON_VIRTUALENV: true
   REPOSITORY_SUBTYPE:
-    sh: if type jq &> /dev/null && [ -f package.json ]; then VER="$(jq -r .blueprint.subgroup package.json)"; if [ "$VER" == null ]; then echo "$REPOSITORY_TYPE"; else echo "$VER"; fi; else echo "$REPOSITORY_TYPE"; fi
+    sh: |
+      if [ -n "$REPOSITORY_TYPE" ]; then REPO_SUBTYPE="$REPOSITORY_TYPE"; fi
+      if type jq &> /dev/null && [ -f package.json ]; then
+        VER="$(jq -r '.blueprint.subgroup' package.json)"
+        if [ "$VER" == 'null' ]; then
+          if [ -n "$REPO_SUBTYPE" ]; then echo "$REPO_SUBTYPE"; else echo "misc"; fi
+        else
+          echo "$VER"
+        fi
+      else
+        if [ -n "$REPO_SUBTYPE" ]; then echo "$REPO_SUBTYPE"; else echo "misc"; fi
+      fi
   REPOSITORY_TYPE:
-    sh: if type jq &> /dev/null && [ -f package.json ]; then VER="$(jq -r .blueprint.group package.json)"; if [ "$VER" == null ]; then echo "$GROUP_TYPE"; else echo "$VER"; fi; else echo "$GROUP_TYPE"; fi
+    sh: |
+      if [ -n "$GROUP_TYPE" ]; then REPO_TYPE="$GROUP_TYPE"; fi
+      if type jq &> /dev/null && [ -f package.json ]; then
+        VER="$(jq -r '.blueprint.group' package.json)"
+        if [ "$VER" == 'null' ]; then
+          if [ -n "$REPO_TYPE" ]; then echo "$REPO_TYPE"; else echo "misc"; fi
+        else
+          echo "$VER"
+        fi
+      else
+        if [ -n "$REPO_TYPE" ]; then echo "$REPO_TYPE"; else echo "misc"; fi
+      fi
   SEMANTIC_CONFIG: semantic-release-config
   TIMEZONE: America/New_York
-  includes:
-    common:start: ./.config/taskfiles/common/Taskfile-start.yml
+
 env:
   OSTYPE:
     sh: |
@@ -207,6 +230,7 @@ env:
     sh: |
       DSN="$(jq -r '.blueprint.sentryDSN' package.json)"
       if [ "$DSN" != 'null' ]; then echo "$DSN"; fi
+
 profile: |
   PATH="$PATH:$HOME/.local/bin:$HOME/.poetry/bin"
   if [[ "$OSTYPE" == 'linux-gnu'* ]] || [[ "$OSTYPE" == 'linux-musl'* ]]; then
@@ -226,6 +250,7 @@ profile: |
   if [ -f .venv/bin/activate ]; then
     . .venv/bin/activate
   fi
+
 tasks:
   build:
     deps:
@@ -250,6 +275,7 @@ tasks:
         else
           [[ $- == *i* ]] && task prepare || (.config/log error '{{.NONINTERACTIVE_MISSING_BUILD_CMD}}' && exit 1)
         fi
+
   clean:
     desc: Removes optional folders that are cached during various tasks
     summary: |
@@ -260,11 +286,13 @@ tasks:
       which will re-generate the project from scratch. Ideally, this task and the reset task
       should never be necessary. The `start` task should be used instead.
     vars:
-      CLEAN_TARGETS: .autodoc .cache .task .venv node_modules tsconfig.tsbuildinfo venv .variables.json
+      CLEAN_TARGETS: .autodoc .cache .task .venv node_modules tsconfig.tsbuildinfo venv
+        .variables.json
     cmds:
       - task: common:clean
         vars:
           CLEAN_TARGETS: '{{.CLEAN_TARGETS}}'
+
   commit:
     desc: Lint staged files, report spelling errors, and open a _required_ commit dialoge
     summary: |
@@ -281,6 +309,7 @@ tasks:
       to your regular `git commit -m` command to bypass the pre-commit hook.
     cmds:
       - task: common:commit
+
   commit:all:
     deps:
       - install:software:git
@@ -310,22 +339,32 @@ tasks:
     cmds:
       - |
         {{if .CLI_ARGS}}
+        task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
         git add --all
         HUSKY=0 git commit -m "{{.CLI_ARGS}}" --no-verify
         {{else}}
+        task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
         git add --all
         git commit
         {{end}}
+
   commit:quick:
+    deps:
+      - ci:commit:config
     cmds:
-      - git add --all
-      - "HUSKY=0 git commit -m '\U0001F527 chore(tweak)": quick minor update' --no-verify
+      - |
+        task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
+        git add --all
+      - HUSKY=0 git commit -m '🔧 chore(tweak): quick minor update' --no-verify
       - git push origin master
+
   devcontainer:
     deps:
       - install:npm:devcontainer
       - install:software:docker
+
   donothing: 'true'
+
   fix:
     desc: Run code auto-fixers / auto-formatters
     summary: |
@@ -336,6 +375,7 @@ tasks:
       an error so the auto-fixes still have to be validated.
     cmds:
       - task: fix:all
+
   get:links:
     deps:
       - install:software:jq
@@ -348,6 +388,7 @@ tasks:
     cmds:
       - .config/log info 'GitHub -----> `{{.GITHUB_URL}}`'
       - .config/log info 'GitLab -----> `{{.GITLAB_URL}}`'
+
   group:exec:
     desc: Execute group commands on any GitLab group (including repositories in sub-groups)
     summary: |
@@ -368,6 +409,7 @@ tasks:
       Be sure to wrap the command in quotes or you might observe some odd behavior.
     cmds:
       - task: git:gitlab:group:exec
+
   init:
     deps:
       - install:software:jq
@@ -399,8 +441,8 @@ tasks:
     cmds:
       - git init
       - task: repair
-      - task: ci:commit
-      - task: ci:synchronize
+      - task: prepare
+
   lint:
     desc: Lints the project using all linters
     summary: |
@@ -414,6 +456,7 @@ tasks:
       `task lint`
     cmds:
       - task: lint:all
+
   livereload:
     deps:
       - install:npm:nodemon
@@ -453,10 +496,12 @@ tasks:
           .config/log error '`Taskfile-project.yml` must exist and have a `livereload` task to use with `nodemon`' && exit 1
         fi
       - nodemon --config {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.config/nodemon.json{{end}}
+
   new:project:
     desc: Create a new project
     cmds:
       - task: prepare
+
   preload:
     desc: Set up your workstation in advance by installing commonly used programs
     summary: |
@@ -499,6 +544,7 @@ tasks:
       - task: install:pipx:bundle
       - task: install:python:requirements
       - task: install:modules:local
+
   prepare:
     desc: Prepares the project for the normal start command
     summary: |
@@ -515,6 +561,7 @@ tasks:
     cmds:
       - task: boilerplate:check:package
       - task: boilerplate:clean
+
   publish:
     desc: Publish a semantic release via `semantic-release`
     summary: |
@@ -562,6 +609,7 @@ tasks:
       success: Successfully ran `semantic-release` via `task publish`
     cmds:
       - task: publish:semantic-release
+
   publish:force:
     desc: Force a `semantic-release` even if there are no new eligible commits
     summary: |
@@ -587,8 +635,10 @@ tasks:
       start: Publishing `semantic-release` update via `task publish:force`
       success: Successfully published update via `task publish:force`
     cmds:
-      - "HUSKY=0 git commit -a --allow-empty -m '\U0001F528 build(version bump): semantic-release {{.UPDATE_LEVEL}}' -n\n"
+      - |
+        HUSKY=0 git commit -a --allow-empty -m '🔨 build(version bump): semantic-release {{.UPDATE_LEVEL}}' -n
       - task: publish
+
   pull:upstream:
     desc: Pull from upstream repositories
     summary: |
@@ -605,18 +655,17 @@ tasks:
       success: Successfully pulled from `upstreamRemotes`
     cmds:
       - task: common:update:upstream:remotes:pull
+
   repair:
     cmds:
-      - |
-        TMP="$(mktemp)" && curl -sSL {{.MODEL_TASKFILE}} > "$TMP"
-        .config/log info 'Ensuring new additions to the model `Taskfile.yml` are present in the project `Taskfile.yml`'
-        yq eval-all -i 'select(fileIndex == 0) * select(fileIndex == 1)' "$TMP" Taskfile.yml
+      - task: common:repair
       - |
         if [ -n "$UPDATE_INIT_SCRIPT" ]; then
           bash <(curl -sSL "$UPDATE_INIT_SCRIPT")
         else
           bash <(curl -sSL {{.INIT_SCRIPT}})
         fi
+
   reset:
     desc: Resets the project by removing all caches and then re-generating templated files
     summary: |
@@ -628,6 +677,7 @@ tasks:
       updates, it re-generates any templated files.
     cmds:
       - task: common:reset
+
   reset:force:
     desc: 'Aggressively reset the project (**WARNING** This will wipe uncommitted work)'
     summary: |
@@ -646,6 +696,7 @@ tasks:
       answer:
         cmds:
           - task: common:reset:force
+
   scripts:
     interactive: true
     deps:
@@ -663,6 +714,7 @@ tasks:
       start: Running `NTL_RUNNER={{.NPM_PROGRAM}} {{.NPX_HANDLE}}ntl`
     cmds:
       - NTL_RUNNER={{.NPM_PROGRAM}} {{.NPX_HANDLE}}ntl
+
   services:
     desc: Update elements of the repository that require API access
     summary: |
@@ -675,6 +727,7 @@ tasks:
       - task: common:update:services
     status:
       - '[ -n "$GITLAB_CI" ] && [ "$REPOSITORY_UPDATE" != "true" ]'
+
   shell:
     desc: Start a terminal session using Docker with any Linux operating system
     compile: |
@@ -708,7 +761,32 @@ tasks:
       * ubuntu-21.04
     cmds:
       - task: common:shell
+
   start:
+    desc: Start the project by installing / updating dependencies, repairing issues, and opening a tutorial
+    summary: |
+      # Start the Project
+
+      This task does everything that running `bash start.sh` does plus a little bit more:
+
+      1. Installs Homebrew if it is not already installed
+      2. Ensures Bodega is installed and up-to-date
+      3. Ensures common system dependencies and runtimes
+      4. Installs commonly used CLI tools
+      5. Ensures local dependencies such as `node_modules` are installed
+      6. Attempts to repair the project if it detects any issues
+
+      It basically sets up all the tools you need, in advance so that problems can be detected as early
+      as possible. In some cases, this command will open documentation or a tutorial to read while dependencies are being
+      installed.
+    log:
+      error: Yikes! Error starting the project!
+      start: Starting the project..
+      success: Project started!
+    cmds:
+      - task: common:start
+
+  synchronize:
     desc: Set up the project and refresh it with the latest changes
     summary: |
       # Start the Project
@@ -727,7 +805,37 @@ tasks:
       start: Synchronizing project with upstream file changes and bootstrapping
       success: Successfully synchronized the project with upstream file changes and also bootstrapped the project
     cmds:
-      - task: upstream:project
+      - task: upstream:{{.PROJECT_TYPE}}
+
+  tag:deps:
+    desc: Inject a new command in the `Taskfile.yml` that includes all tasks matching a given tag as deps
+    summary: |
+      # Create Task with Deps Based on Tag
+
+      Use this task to inject a new task in the `Taskfile.yml` that includes all the tasks
+      that are tagged with a certain tag as deps. The tag must be supplied as a CLI argument.
+
+      Say you have a task that looks like this:
+
+      ```
+      my-task:
+        tags:
+          - docker
+        cmds:
+          - docker volume ls
+      ```
+
+      Then, by running `task tag:deps -- docker`, you will get the following task injected into the
+      `Taskfile.yml` file:
+
+      ```
+      deps:docker:
+        deps:
+          - my-task
+      ```
+    cmds:
+      - task: common:util:task:tag:deps
+
   template:
     deps:
       - install:npm:liquidjs
@@ -749,6 +857,7 @@ tasks:
     preconditions:
       - sh: test -f .variables.json
         msg: This task requires that you have already spun up the project by running `task start`
+
   test:
     deps:
       - install:software:jq
@@ -779,8 +888,26 @@ tasks:
         else
           [[ $- == *i* ]] && task prepare || (.config/log error '{{.NONINTERACTIVE_MISSING_TEST_CMD}}' && exit 1)
         fi
+
   update:
-    desc: Update the repository
+    desc: Fully update the repository
+    summary: |
+      # Update the Repository / Project
+
+      This task will:
+
+      1. Ensure Homebrew is installed
+      2. Ensure runtimes like Node.js, Go, Python, and Poetry are installed
+      3. Ensure the `PATH` environment variable is properly configured
+      4. Configure the environment if it is in a `$CI` environment
+      5. Run a repair script that is used to ensure older repositories are compatible with the Taskfile scripts
+      6. Prepare the repository by automatically setting up certain parts of the project
+      7. Run a full update on the repository with `task start`
+      8. Automatically commit changes
+      9. Update GitLab/GitHub repository settings if the `GITHUB_TOKEN` / `GITLAB_TOKEN` variables are set
+
+      Along the way, if any dependencies are missing they will be installed as well just like with all of the
+      tasks included in these Taskfiles.
     log:
       error: Failed to update the repository
       start: Updating the repository..
@@ -788,4 +915,4 @@ tasks:
     cmds:
       - task: common:start
         env:
-          UPDATE_PROJECT: "true"
+          UPDATE_PROJECT: 'true'
