🔧 chore(latest): latest

diff --git a/.config/taskfiles/fix/Taskfile.yml b/.config/taskfiles/fix/Taskfile.yml
--- a/.config/taskfiles/fix/Taskfile.yml
+++ b/.config/taskfiles/fix/Taskfile.yml
@@ -24,10 +24,9 @@ tasks:
       - :install:modules:local
       - :install:npm:eslint
       - :install:software:expect
-    desc: Fix JavaScript/TypeScript errors automatically
-    hide: '{{not (has .REPOSITORY_TYPE (list "angular" "npm"))}}'
+    desc: Fix ESLint errors automatically
     summary: |
-      # Fix JavaScript/TypeScript Errors with ESLint
+      # Fix Errors with ESLint Automatically
 
       This task is an [`eslint`](https://eslint.org/) task. It will attempt to automatically fix
       `eslint` issues. It will report any issues it was unable to fix. The configuration found in
@@ -36,7 +35,7 @@ tasks:
       **Example using `eslint` to fix a single JS/TS file:**
       `task fix:js -- single.ts`
 
-      **Example fixing all JS/TS files in a project:**
+      **Example fixing all files in a project:**
       `task fix:js`
     log:
       error: ESLint found some issues that need to be fixed manually
@@ -60,6 +59,22 @@ tasks:
           done
         fi
       - rm eslint.log
+
+  eslint:staged:
+    deps:
+      - :install:modules:local
+      - :install:npm:eslint
+    desc: Auto-fix only modified files with ESLint
+    env:
+      ESLINT_STAGED_ONLY: on
+    log:
+      error: Failed to auto-fix modified files with ESLint
+      start: Auto-fixing modified files with ESLint
+      success: Successfully auto-fixed modified files with ESLint
+    cmds:
+      - >
+        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
+        --cache-location .cache/eslintcache --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   go:
     desc: Fix Go with all available Go fixers
@@ -124,6 +139,38 @@ tasks:
     cmds:
       - '{{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --cache --cache-location .cache/eslintcache --fix
         --format pretty --ext .json {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+
+  markdown:
+    deps:
+      - :install:npm:markdown-table-formatter
+    desc: Auto-fixes markdown files
+    summary: |
+      # Auto-Fix Markdown Files
+
+      This task performs various tasks that cleanup markdown files. It currently:
+
+      1. Runs `markdown-table-formatter` which fixes up markdown tables
+
+      You can either pass a file as a CLI argument or run it without a CLI argument to
+      auto-fix all the markdown files in the project that are not ignored by .gitignore.
+
+      **Example running against whole project:**
+      `task fix:markdown`
+
+      **Example running on single file:**
+      `task fix:markdown -- README.md`
+    log:
+      error: Error encountered while auto-fixing markdown file(s)
+      start: Auto-fixing markdown file(s)
+      success: Successfully finished auto-fixing markdown file(s)
+    cmds:
+      - >
+        {{if .CLI_ARGS}}
+        markdown-table-formatter {{.CLI_ARGS}}
+        {{else}}
+        find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.md' \)
+        -print0 | xargs -0 -r -n1 markdown-table-formatter
+        {{end}}
 
   misc:
     deps:
@@ -242,12 +289,13 @@ tasks:
     log:
       start: Running Prettier on {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}project{{end}}
     cmds:
-      - |
-        {{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
-        if [ -n "$EXIT_CODE" ]; then
-          .config/log warn 'Failed to run `{{.NPX_HANDLE}}prettier` - falling back to `prettier`'
-          prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
-        fi
+      - cmd: |
+          {{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
+          if [ -n "$EXIT_CODE" ]; then
+            .config/log warn 'Failed to run `{{.NPX_HANDLE}}prettier` - falling back to `prettier`'
+            prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+          fi
+        ignore_error: true
 
   python:
     deps:
@@ -324,6 +372,23 @@ tasks:
         {{else}}
           find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.sh' -o -name '*.sh.j2' \) \
             -print0 | xargs -0 {{.NPX_HANDLE}}shellcheck -e {{.SHELLCHECK_EXCLUDE}} -f diff | git apply
+        {{end}}
+
+  spelling:markdown:
+    deps:
+      - :install:go:misspell
+    desc: Auto-fix spelling errors in markdown files using `misspell`
+    log:
+      error: Encountered error while attempting to auto-correct spelling mistakes with `misspell`
+      start: Auto-fixing using the `misspell` spell-check engine
+      success: Successfully auto-fixed files using `misspell`
+    cmds:
+      - >
+        {{if .CLI_ARGS}}
+        misspell -w {{.CLI_ARGS}}
+        {{else}}
+        find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.md' \)
+        -print0 | xargs -0 -r -n1 misspell -w
         {{end}}
 
   toml:
